name: major-version-tag
inputs:
  version:
    required: true
runs:
  using: composite
  steps:
      shell: bash
    - run: |
        version=${{ inputs.version }}
        MAJOR_VERSION=${version:0:2}.0
        echo "::set-output name=major_version::$MAJOR_VERSION"