name: 'major version tag'
description: 'return the major version for a given version'
inputs:
  version:
    required: true
runs:
  using: 'composite'
  steps:
    - run: |
        version=${{ inputs.version }}
        MAJOR_VERSION=${version:0:2}.0
        echo "major version is $MAJOR_VERSION"
        echo "::set-output name=major_version::$MAJOR_VERSION"
      shell: bash