# uses https://github.com/justmiles/go-markdown2confluence to publish specified document(s) to Confluence
name: publish-to-confluence-shared-workflow
on:
  workflow_call:
    inputs:
      comment:
        description: Add an optional comment to the published page.
        required: false
        type: string
      exclude:
        description: List of exclude file patterns (regex) that will be applied on markdown file paths.
        required: false
        type: string
      modified_since:
        description: Only upload files that have modifed in the past n minutes.
        required: false
        type: number
      parent:
        description: Optional parent page to nest content under.  Separate multiple parent pages with /.
        required: false
        type: string
      space:
        description: Confluence space under which content should be published.  Default TXM.
        required: false
        default: TXM
        type: string
      title:
        description: Set the page title on upload (defaults to filename without extension).
        required: false
        type: string
      use_document_title:
        description: Will use the Markdown document title (# Title) if available.  Default false.
        required: false
        default: false
        type: boolean
      documents:
        description: The documents to upload.  Can be a directory of documents or a single file.  Default is README.md.
        required: false
        default: README.md
        type: string

    outputs:
      publish_url:
        value: ${{ jobs.publish-to-confluence.outputs.publish_url }}

jobs:
  publish-to-confluence:
    runs-on: ubuntu-latest

    container:
      image: nexus.txm.tools/golang:latest
      credentials:
        username: ${{ secrets.NEXUS_USER_CI_DOCKER }}
        password: ${{ secrets.NEXUS_PASSWORD_CI_DOCKER }}
      env:
        CONFLUENCE_USERNAME: oe@tempus-ex.com
        CONFLUENCE_PASSWORD: ${{ secrets.MARKDOWN_CONFLUENCE }}
        CONFLUENCE_ENDPOINT: https://epf.atlassian.net/wiki

    permissions: write-all

    outputs:
      publish_url: ${{ steps.handle-inputs.outputs.publish_url }}

    steps:
      - name: download and install markdown2confluence
        run: |
          curl -LO https://github.com/justmiles/go-markdown2confluence/releases/download/v3.4.6/go-markdown2confluence_3.4.6_linux_x86_64.tar.gz
          tar -xzvf go-markdown2confluence_3.4.6_linux_x86_64.tar.gz -C /usr/local/bin/ markdown2confluence

      - name: checkout git repo
        uses: actions/checkout@v3

      - name: grant permission for unsafe repository
        run: |
          git config --global --add safe.directory /__w/${{ github.event.repository.name }}/${{ github.event.repository.name }}

      - name: handle inputs
        id: handle-inputs
        run: |
          echo "parent=${{ github.event.inputs.parent }}" >> $GITHUB_OUTPUT
          echo "title=${{ github.event.inputs.title }}" >> $GITHUB_OUTPUT
          echo "publish_url=flibbityfloooo" >> $GITHUB_OUTPUT
  
  print-some-shit:
      needs: publish-to-confluence
      runs-on: ubuntu-latest
      steps:
        - name: print stuff
          run: |
            echo "parent is ${{ needs.publish-to-confluence.outputs.parent }}"
            echo "title is ${{ needs.publish-to-confluence.outputs.title }}"
            echo "publish_url is ${{ needs.publish-to-confluence.outputs.publish_url }}"
        

